#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"

export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
export VLC_PLUGIN_PATH="${HERE}/usr/lib/vlc/plugins"
export PYTHON_VLC_LIB_PATH="${HERE}/usr/lib/libvlc.so.5"
export QT_QPA_PLATFORM_PLUGIN_PATH="${HERE}/usr/lib/qt6/plugins/platforms"

exec "${HERE}/usr/bin/bandcamp-qt" "$@"
