#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"

export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
export VLC_PLUGIN_PATH="${HERE}/usr/lib/vlc/plugins"
export PYTHON_VLC_LIB_PATH="${HERE}/usr/lib/libvlc.so.5"
export FONTCONFIG_PATH="/etc/fonts"
export FONTCONFIG_FILE="/etc/fonts/fonts.conf"

exec "${HERE}/usr/bin/bandcamp-player" "$@"
